package cartographer.perf.safety;

public enum SaveSafetyViolationType {
    SAVE_EXISTENCE_CHANGED,
    SAVE_FILE_TYPE_CHANGED,
    SAVE_SIZE_CHANGED,
    SAVE_LAST_MODIFIED_CHANGED,
    SAVE_CONTENT_CHANGED,
    WAL_CREATED,
    WAL_REMOVED,
    WAL_FILE_TYPE_CHANGED,
    WAL_SIZE_CHANGED,
    WAL_LAST_MODIFIED_CHANGED,
    WAL_CONTENT_CHANGED,
    SHM_CREATED,
    SHM_REMOVED,
    SHM_FILE_TYPE_CHANGED,
    SHM_SIZE_CHANGED,
    SHM_LAST_MODIFIED_CHANGED,
    SHM_CONTENT_CHANGED,
    JOURNAL_CREATED,
    JOURNAL_REMOVED,
    JOURNAL_FILE_TYPE_CHANGED,
    JOURNAL_SIZE_CHANGED,
    JOURNAL_LAST_MODIFIED_CHANGED,
    JOURNAL_CONTENT_CHANGED
}
