package cartographer.perf.gui;

public enum GuiManualCheck {
    WORKSTATION_REAL_SAVE_SMOKE,
    R2048_VISUAL,
    R4096_ATTEMPT_RECORDED,
    CACHE_COLD_WARM_CORRUPT_HEAL,
    LOCAL_RECOMPOSITION,
    FUSED_PROSPECTING,
    RESPONSIVE_CANCELLATION,
    SOURCE_SAFETY_AFTER_CANCEL,
    P13_DOCK_AND_VIEWPORT_UX
}
